name: nucosmos_pos_app
description: NUCOSMOS POS Flutter app for Android tablets.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  esc_pos_utils_plus: ^2.0.4
  flutter_thermal_printer: ^2.0.1
  http: ^1.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
