export const PERMISSIONS = {
  REPORTS_VIEW: "REPORTS_VIEW",
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  PRODUCTS_VIEW: "PRODUCTS_VIEW",
  PRODUCTS_EDIT: "PRODUCTS_EDIT",
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_EDIT: "INVENTORY_EDIT",
  PROCUREMENT_VIEW: "PROCUREMENT_VIEW",
  PROCUREMENT_EDIT: "PROCUREMENT_EDIT",
  SUPPLIERS_VIEW: "SUPPLIERS_VIEW",
  SUPPLIERS_EDIT: "SUPPLIERS_EDIT",
  ORDERS_VIEW: "ORDERS_VIEW",
  ORDERS_REFUND: "ORDERS_REFUND",
  SHIFTS_VIEW: "SHIFTS_VIEW",
  SHIFTS_EDIT: "SHIFTS_EDIT",
  DEVICES_VIEW: "DEVICES_VIEW",
  USERS_VIEW: "USERS_VIEW",
  USERS_EDIT: "USERS_EDIT",
  ROLES_VIEW: "ROLES_VIEW",
  ROLES_EDIT: "ROLES_EDIT",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
